### ISSUE TITLE
Call to undefined function sqlsrv_connect()

### ISSUE THREAD

**Issue by wblaircox** [mevdschee/mysql-crud-api#1]
Hi,

This looks exactly what I need and have spent days looking for! Alas, I was greeted with;

Fatal error: Call to undefined function sqlsrv_connect() in /home/....../api.php on line 300

I followed the setup instructions and poked around. Not sure if I'm doing something wrong? 

MySQL on Apache (Cpanel), InnoDB. I see that the sqlsrv_connect is a php parameter - perhaps not available in my build?

Please advise.
:)

**Comment by mevdschee** [comment]
Hi! Tell me a little more on what you did and try to achieve? Do you want to connect to MsSQL or to MySQL?

**Comment by wblaircox** [comment]
Hi,

MySQL on a Linux system. That php function is for Microsoft SQL. Do you
support MySQL on Linux? How do I configure it?

**Comment by mevdschee** [comment]
I do, please check my last commit

**Comment by wblaircox** [comment]
Awesome, thank you! Works perfectly. Howerver, how do I do one of the two?


   1. Perform List + Transform + Filter?
   2. Or, permanently activate transform to objects so the output can be
   the proper format?

Thanks!

**Comment by mevdschee** [comment]
OK good that you figured it out. Good luck with it!

**Comment by wblaircox** [comment]
Working awesome, you saved the day!!! :)
