### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by MaccerC** [mevdschee/mysql-crud-api#2]
I've set these lines to my settings: 
$api = new MySQL_CRUD_API(array(
        'hostname'=>'localhost',
	'username'=>'xxx',
	'password'=>'xxx',
	'database'=>'xxx'
));
However I get a 'not found (entity)' error.
What am I doing wrong?

**Comment by mevdschee** [comment]
Did you add the name of a table to your URL?

**Comment by MaccerC** [comment]
I use this URL: http://localhost/~username/api.php
(as you've noticed probably: I'm on a mac)
Where should I put the table name?

**Comment by mevdschee** [comment]
Like this: 

http://localhost/~username/api.php/tablename

**Comment by MaccerC** [comment]
Great! That works. It shows me all the records found in that table. Thanks for the answer. 

Now i want to use this API in an angular application. Therefor I need the result as a JSON output. Am I right to append your '?transform=1' method to get a json output? However when I use $http.get("api.php/bml?transform=1").success(function(data){
			$scope.records = data;
	  });
 I get no result. Note: 'bml' is the table name.
I'm running this application on localhost.

**Comment by mevdschee** [comment]
Instead of 

api.php/bml?transform=1

Try the full URL.

Also use the debugger to see what's going on.

Good luck.
