### ISSUE TITLE
Can't use time as filter

### ISSUE THREAD

**Issue by dvukeli1** [mevdschee/mysql-crud-api#4]
I try to use TIMESTAMP as filter because I need time sampled data ( 1 day, 2 days ....) but without any success.  Is there any way to use DATE(NOW()) or  INTERVAL  in filter ?

**Comment by mevdschee** [comment]
I suppose you cannot use a DATETIME typed field and use:

        created_at,gt,2015-09-21 18:00:00

Or can you?

**Comment by dvukeli1** [comment]
Yes thank you. This is helpful and I can use it in that way.

**Comment by mevdschee** [comment]
Great! Good luck with your project.

**Comment by simonbuehler** [comment]
hi,

is there a way to filter TIMESTAMP in the meantime? Unfortunately, i can't change the TIMESTAMP to DATETIME  -thx
